name: 'build-cakeml'
description: 'Build the cakeml project'
inputs:
  hol-branch:
    description: 'Which HOL branch to use'
    required: false
    default: 'master'
  polyml-version:
    description: 'Which PolyML version to use'
    required: false
    default: '5.7.1'
outputs:
  hol-hash:
    description: "HOL4 commit"
    value: ${{ steps.hol-pull.outputs.hash }}
  polyml-hash:
    description: "PolyML commit"
    value: ${{ steps.poly-pull.outputs.hash }}
runs:
  using: composite
  steps:
    - shell: bash
      run: |
        sudo apt-get update
        sudo apt-get install git build-essential
    - id: poly-pull
      uses: actions/checkout@v2
      with:
        repository: polyml/polyml
        ref: ${{ inputs.polyml-version }}
        path: polyml
      shell: bash
      run: echo "::set-output name=hash::$(git show-ref --hash HEAD)"
    - working-directory: polyml
      shell: bash
      run: |
        configure --prefix=`pwd`
        make
        make compiler
        make install
    - id: hol-pull
      uses: actions/checkout@v2
      with:
        repository: polyml/polyml
        ref: ${{ inputs.hol-branch }}
        path: HOL
      shell : bash
      run: echo "::set-output name=hash::$(git show-ref --hash HEAD)"
    - working-directory: polyml
      shell: bash
      run: |
        echo BUILDS_HOL
